[package]
name = "vexl-ir"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
vexl-core = { path = "../vexl-core" }
vexl-syntax = { path = "../vexl-syntax" }
vexl-types = { path = "../vexl-types" }
