[package]
name = "vexl-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
vexl-core = { path = "../vexl-core" }
vexl-gpu = { path = "../vexl-gpu" }
parking_lot = "0.12"
lazy_static = "1.4"
log = "0.4"
anyhow = "1.0"
crossbeam-deque = "0.8"
